### ISSUE TITLE
사용자의 로그인 상태 구별을 개선해 주세요

### ISSUE THREAD

**Issue by OutOfBedlam** [Solution-Global/teamon#1]
- [ ] Bug Report
- [x] Improvement
- [ ] Request for new feature

좌측 사용자 리스트에서 로그오프 상태의 사용자의 스크린명의 색상을 좀 더 색으로 하던가 로그인 상태의 사용자의 색상을 화이트에 가깝게 하던가해서 사용자의 온/오프 상태가 좀 더 구별되도록 하면 어떨까요?

**Comment by jingjingea** [comment]
git 에 이런 기능이 있네요. 저는 테두리 색을 밝은 색으로 햇으면 좋겠어요.

**Comment by antonio91kim** [comment]
@OutOfBedlam "좀 더 색"은 어떤 색인가요...
@jingjingea 밝은 색이라면 무슨 색? 16진수로 알려주면 좋고요.

**Comment by jerrian** [comment]
처음 접하는 사람들에게 테두리만으로 로그인 여부를 판단하는 것이 불명확해 보이나 봅니다. skype, slack 등과 같이 좀더 직관적인 부가 아이콘 등이 필요하지 않나 싶네요.
