### ISSUE TITLE
프로파일 사진 바꾸기

### ISSUE THREAD

**Issue by OutOfBedlam** [Solution-Global/teamon#2]
> Issue Type
- [x] Bug Report
- [ ] Improvement
- [ ] Request for new feature

> OS
- [ ] Windows
- [ ] Mac
- [x] Common
## Description

웹 버전에서 프로파일 이미지 변경을 선택하고 팝업 창에 이미지 파일을 끌어다 넣으면 이미지가 표시된 상태에서 올라가지 않습니다. Upload Profile Image 버튼을 눌러도 아무 변화가 없습니다.
시험 환경 Mac, Safari.

<img width="584" alt="screen shot 2016-04-07 at 11 46 59 am" src="https://cloud.githubusercontent.com/assets/7237878/14339053/78bb6878-fcb6-11e5-8ae0-0ed2a6c0ab8c.png">

<img width="564" alt="screen shot 2016-04-07 at 11 48 54 am" src="https://cloud.githubusercontent.com/assets/7237878/14339079/bf2921ba-fcb6-11e5-84e1-3bab4cc11cfa.png">

**Comment by antonio91kim** [comment]
Upload profile image 버튼을 눌러보셨나요?

**Comment by antonio91kim** [comment]
어두운 이미지이기 때문에 안올라갑니다...라고 말하고 싶지만
현재 고치고 있습니다. 수정된 버전이 배포되면 알려드릴께요.

**Comment by antonio91kim** [comment]
소스코드상에 버그가 있어서 파일 업로드가 되지 않고 있었습니다.
곧 fix된 버전 배포할께요.

**Comment by antonio91kim** [comment]
이건 해결됐으니까 close 할께요.
