### ISSUE TITLE
채널 추가 아이콘 교체 의견

### ISSUE THREAD

**Issue by OutOfBedlam** [Solution-Global/teamon#4]
> Issue Type
- [ ] Bug Report
- [x] Improvement
- [ ] Request for new feature

> OS
- [ ] Windows
- [ ] Mac
- [x] Common
## Description

채널 추가하는 아이콘이 좀 이질적이어서 바꾸는게 어떨 까요?

![channel_add](https://cloud.githubusercontent.com/assets/7237878/14375202/f30472e4-fd99-11e5-9d4b-e57acfa7fdb8.jpg)

아이콘 그려달라고 할 까봐서  font-awesome의 아이콘 추천합니다.

![plus_icons](https://cloud.githubusercontent.com/assets/7237878/14375205/f83dddfe-fd99-11e5-9aee-c94ca98f883d.jpg)

plus
plus circle
plus square
plus square o

**Comment by jingjingea** [comment]
3번요~
