### ISSUE TITLE
맥용 인스톨러 배경

### ISSUE THREAD

**Issue by OutOfBedlam** [Solution-Global/teamon#7]
> Issue Type
- [ ] Bug Report
- [x] Improvement
- [ ] Request for new feature

> OS
- [ ] Windows
- [x] Mac
- [ ] Common
## Description

![mac_installer](https://cloud.githubusercontent.com/assets/7237878/14380531/e80f9df2-fdba-11e5-9194-42ceed97808f.jpg)

**Comment by antonio91kim** [comment]
이건 어떠세요?
물론 아이콘 두개는 적당한 위치에 올라갈 예정입니다.
![mac_background](https://cloud.githubusercontent.com/assets/11921551/14517093/90b1470c-0244-11e6-8f43-c179964fd3e3.jpg)

**Comment by OutOfBedlam** [comment]
👍
