### ISSUE TITLE
비디오 콜을 누르면 아무런 반응이 없음

### ISSUE THREAD

**Issue by seo5273** [Solution-Global/teamon#8]
> Issue Type
- [x] Bug Report
- [ ] Improvement
- [ ] Request for new feature

> OS
- [ ] Windows
- [x] Mac
- [ ] Common
## Description

... description for the problem ...

비디오 콜을 누르면 아무런 반응이 없음

**Comment by OutOfBedlam** [comment]
통화를 위한 WebRTC 게이트웨이가 TeamOn이 아닌 다른 개발건의 시험과정에서 예상치 못한 호 플로우가 진행되어 잠시 죽어 있었습니다. 지금은 방어 로직이 반영되었을 것으로 예상합니다.

**Comment by antonio91kim** [comment]
더이상 동일한 문제가 없는 것으로 판단하여 해당 issue를 close하겠습니다. 동일한 문제 발생시 reopen해주세요.
